config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "search" => "searches#search"
  resources :users
  resources :portfolios do
    resources :reviews, only: [:index, :create]
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :portfolio_tags, dependent: :destroy
  has_many :tags, through: :portfolio_tags
  attachment :image
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

  def save_tags(saveportfolio_tags)
    # 現在のユーザーの持っているskillを引っ張ってきている
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 今portfolioが持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
    old_tags = current_tags - saveportfolio_tags
    # 今回保存されたものと現在の差を新しいタグとする。新しいタグは保存
    new_tags = saveportfolio_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      portfolio_tag = Tag.find_or_create_by(name:new_name)
      # 配列に保存
      self.tags << portfolio_tag
    end
  end

  def self.search_for(content, method)
      if method == 'perfect'
        Portfolio.where(title: content)
      elsif method == 'forward'
        Portfolio.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        Portfolio.where('title LIKE ?', '%'+content)
      else
        Portfolio.where('title LIKE ?', '%'+content+'%')
      end
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @portfolios = Portfolio.all.order(id: "DESC")
  end

  def show
    @portfolio = Portfolio.find(params[:id])
    @review = Review.new
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    @portfolio.user_id = current_user.id
    tag_list = params[:portfolio][:tag_name].split(',')
    if @portfolio.save
      @portfolio.save_tags(tag_list)
      redirect_to portfolio_path(@portfolio), notice: "ポートフォリオを投稿しました。"
    else
      @portfolios = Portfolio.all
      render :new
    end
  end

  def edit
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.user != current_user
      redirect_to portfolios_path, alert: "不正なアクセスです。"
    end
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    tag_list = params[:portfolio][:tag_name].split(',')
    if @portfolio.update(portfolio_params)
      @portfolio.save_tags(tag_list)
      redirect_to portfolio_path(@portfolio), notice: "ポートフォリオを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    portfolio = Portfolio.find(params[:id])
    portfolio.destroy
    redirect_to user_path(portfolio.user), notice: "ポートフォリオを削除しました。"
  end

  private
  def portfolio_params
    params.require(:portfolio).permit(:title, :body, :image, :comment)
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/edit.html.erb
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ポートフォリオ編集
      </h1>
    </div>
  </div>
</section>

<% if @portfolio.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @portfolio.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @portfolio, local: true do |f| %>
          <div class="field">
            <%= f.label :title, "ポートフォリオ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :tag_name, "カテゴリー", class: "label" %>
            <%= f.text_field :tag_name, class: 'input' %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit "投稿", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/portfolios/index.html.erb
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ポートフォリオ一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @portfolios.each do |portfolio| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to portfolio_path(portfolio) do %>
                  <%= attachment_image_tag portfolio, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag portfolio.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%= link_to portfolio.user.username, user_path(portfolio.user) %></div>
                </div>
              </div>

              <div class="card-content">
                <div class="content">
                  <div class="content average-score">
                    <div class="star-rating mb-2">
                      <div class="star-rating-front" style="width: <%= portfolio.review_score_percentage %>%">★★★★★</div>
                      <div class="star-rating-back">★★★★★</div>
                    </div>
                    <div class="average-score-display ml-3 pt-2">
                      <%= portfolio.avg_score %>点（<%= portfolio.reviews.count %>件のレビュー）
                    </div>
                  </div>
                </div>
              </div>
              <footer class="card-footer">
                <%= link_to portfolio_reviews_path(portfolio), class: "button card-footer-item" do %>
                  レビューを見る
                <% end %>
                <%= link_to portfolio_path(portfolio), class: "button card-footer-item" do %>
                  レビューを書く
                <% end %>
              </footer>

              <div class="content">
                <time><%= portfolio.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/portfolios/new.html.erb
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規ポートフォリオ投稿
      </h1>
    </div>
  </div>
</section>

<% if @portfolio.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this object being saved: not successfully</h2>
    <ul>
      <% @portfolio.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @portfolio, local: true do |f| %>
          <div class="field">
            <%= f.label :title, "ポートフォリオ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :tag_name, "カテゴリー", class: "label" %>
            <%= f.text_field :tag_name, class: 'input' %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit "投稿", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/portfolios/show.html.erb
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ポートフォリオ詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @portfolio, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @portfolio.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>詳細</th>
                </tr>
                <tr>
                  <td><%= simple_format @portfolio.body %></td>
                </tr>
                <tr>
                  <th>カテゴリー</th>
                </tr>
                <tr>
                  <td>
                    <% @portfolio.tags.each do |tag| %>
                      <li style="list-style: none;"><%= link_to tag.name, search_path(content: tag.name, model:"tag", method: "perfect") %></li>
                    <% end %>
                  </td>
                </tr>
              </table>
              <div class="card-content">
                <div class="content average-score">
                  <div class="star-rating mb-2">
                    <div class="star-rating-front" style="width: <%= @portfolio.review_score_percentage %>%">★★★★★</div>
                      <div class="star-rating-back">★★★★★</div>
                  </div>
                  <div class="average-score-display ml-3 pt-2">
                    <%= @portfolio.avg_score %>点（<%= @portfolio.reviews.count %>件のレビュー）
                  </div>
                </div>
              </div>
              <% if @portfolio.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_portfolio_path(@portfolio), class: "button is-success" %>
              <% end %>
            </div>
            <%= render 'reviews/form', review: @review, portfolio: @portfolio %>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @portfolio.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @portfolio.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@portfolio.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @portfolio.user.username %> さんのページ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>